exclude: "^pixi.lock$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=8192]
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
        exclude: "notebooks/.*\\.ipynb$"
      - id: trailing-whitespace
        exclude: "notebooks/.*\\.ipynb$"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: "notebooks/.*\\.ipynb$"
      - id: ruff-format
        exclude: "notebooks/.*\\.ipynb$"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: "notebooks/.*\\.ipynb$"
        args: ["--skip=*.js,*.html,*.css"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: local
    hooks:
      - id: pixi-lock-check
        name: pixi-lock-check
        entry: bash -c "pixi lock --check"
        stages: [pre-push]
        language: system
        pass_filenames: false
