# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/j35/git/python_notebooks/notebooks/ui/ui_resonance_imaging_layers_input.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layer_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.layer_groupBox.setObjectName("layer_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layer_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.example_table = QtWidgets.QTableWidget(self.layer_groupBox)
        self.example_table.setEnabled(False)
        self.example_table.setMaximumSize(QtCore.QSize(16777215, 50))
        self.example_table.setObjectName("example_table")
        self.example_table.setColumnCount(5)
        self.example_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.example_table.setItem(0, 4, item)
        self.example_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.example_table)
        self.layer_table = QtWidgets.QTableWidget(self.layer_groupBox)
        self.layer_table.setEnabled(True)
        self.layer_table.setAlternatingRowColors(True)
        self.layer_table.setShowGrid(True)
        self.layer_table.setObjectName("layer_table")
        self.layer_table.setColumnCount(5)
        self.layer_table.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setHorizontalHeaderItem(4, item)
        self.layer_table.horizontalHeader().setSortIndicatorShown(False)
        self.layer_table.horizontalHeader().setStretchLastSection(False)
        self.layer_table.verticalHeader().setVisible(False)
        self.layer_table.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.layer_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.layer_groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.Emin_lineEdit = QtWidgets.QLineEdit(self.layer_groupBox)
        self.Emin_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.Emin_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Emin_lineEdit.setObjectName("Emin_lineEdit")
        self.horizontalLayout_9.addWidget(self.Emin_lineEdit)
        self.label_8 = QtWidgets.QLabel(self.layer_groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.layer_groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.Emax_lineEdit = QtWidgets.QLineEdit(self.layer_groupBox)
        self.Emax_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.Emax_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Emax_lineEdit.setObjectName("Emax_lineEdit")
        self.horizontalLayout_9.addWidget(self.Emax_lineEdit)
        self.label_10 = QtWidgets.QLabel(self.layer_groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.deltaE_label = QtWidgets.QLabel(self.layer_groupBox)
        self.deltaE_label.setObjectName("deltaE_label")
        self.horizontalLayout_9.addWidget(self.deltaE_label)
        self.deltaE_lineEdit = QtWidgets.QLineEdit(self.layer_groupBox)
        self.deltaE_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.deltaE_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.deltaE_lineEdit.setObjectName("deltaE_lineEdit")
        self.horizontalLayout_9.addWidget(self.deltaE_lineEdit)
        self.label_16 = QtWidgets.QLabel(self.layer_groupBox)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.horizontalLayout.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.validate_table_iinputs = QtWidgets.QPushButton(self.layer_groupBox)
        self.validate_table_iinputs.setObjectName("validate_table_iinputs")
        self.horizontalLayout.addWidget(self.validate_table_iinputs)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.layer_groupBox)
        self.check_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.check_groupBox.setEnabled(True)
        self.check_groupBox.setObjectName("check_groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.check_groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.check_groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.layer_name_combobox = QtWidgets.QComboBox(self.check_groupBox)
        self.layer_name_combobox.setObjectName("layer_name_combobox")
        self.horizontalLayout_4.addWidget(self.layer_name_combobox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.check_groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.layer_thickness = QtWidgets.QLabel(self.check_groupBox)
        self.layer_thickness.setObjectName("layer_thickness")
        self.gridLayout.addWidget(self.layer_thickness, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.check_groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.check_groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.layer_density = QtWidgets.QLabel(self.check_groupBox)
        self.layer_density.setObjectName("layer_density")
        self.gridLayout.addWidget(self.layer_density, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.check_groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_11 = QtWidgets.QLabel(self.check_groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.element_name_combobox = QtWidgets.QComboBox(self.check_groupBox)
        self.element_name_combobox.setObjectName("element_name_combobox")
        self.horizontalLayout_5.addWidget(self.element_name_combobox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.check_groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.element_density = QtWidgets.QLabel(self.check_groupBox)
        self.element_density.setObjectName("element_density")
        self.gridLayout_2.addWidget(self.element_density, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.check_groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.check_groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.element_molar_mass = QtWidgets.QLabel(self.check_groupBox)
        self.element_molar_mass.setObjectName("element_molar_mass")
        self.gridLayout_2.addWidget(self.element_molar_mass, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.check_groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.check_groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 2, 1, 1)
        self.element_number_of_atoms = QtWidgets.QLabel(self.check_groupBox)
        self.element_number_of_atoms.setObjectName("element_number_of_atoms")
        self.gridLayout_2.addWidget(self.element_number_of_atoms, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.check_groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.element_table = QtWidgets.QTableWidget(self.check_groupBox)
        self.element_table.setObjectName("element_table")
        self.element_table.setColumnCount(4)
        self.element_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.element_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.element_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.element_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.element_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.element_table)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.check_groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.total_iso_ratio = QtWidgets.QLabel(self.check_groupBox)
        self.total_iso_ratio.setObjectName("total_iso_ratio")
        self.horizontalLayout_8.addWidget(self.total_iso_ratio)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addWidget(self.check_groupBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem9 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setEnabled(False)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_7.addWidget(self.ok_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.validate_table_iinputs.clicked.connect(MainWindow.validate_table_input_clicked)
        self.layer_name_combobox.currentIndexChanged['QString'].connect(MainWindow.layer_combobox_clicked)
        self.element_name_combobox.currentIndexChanged['QString'].connect(MainWindow.element_combobox_clicked)
        self.element_table.cellChanged['int','int'].connect(MainWindow.element_table_edited)
        self.ok_button.clicked.connect(MainWindow.ok_button_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.layer_groupBox.setTitle(_translate("MainWindow", "Layers"))
        item = self.example_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.example_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.example_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Elements"))
        item = self.example_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stoichio. Ratio"))
        item = self.example_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Thickness (mm)"))
        item = self.example_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Density (g/cm3)"))
        __sortingEnabled = self.example_table.isSortingEnabled()
        self.example_table.setSortingEnabled(False)
        item = self.example_table.item(0, 0)
        item.setText(_translate("MainWindow", "my_layer_1"))
        item = self.example_table.item(0, 1)
        item.setText(_translate("MainWindow", "Co, Ag"))
        item = self.example_table.item(0, 2)
        item.setText(_translate("MainWindow", "1,1"))
        item = self.example_table.item(0, 3)
        item.setText(_translate("MainWindow", "20"))
        item = self.example_table.item(0, 4)
        item.setText(_translate("MainWindow", "0.9"))
        self.example_table.setSortingEnabled(__sortingEnabled)
        item = self.layer_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.layer_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.layer_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Elements"))
        item = self.layer_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stoichio. Ratio"))
        item = self.layer_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Thickness (mm)"))
        item = self.layer_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Density (g/cm3)"))
        self.label_5.setText(_translate("MainWindow", "Emin"))
        self.Emin_lineEdit.setText(_translate("MainWindow", "0.001"))
        self.label_8.setText(_translate("MainWindow", "eV"))
        self.label_9.setText(_translate("MainWindow", "Emax"))
        self.Emax_lineEdit.setText(_translate("MainWindow", "300"))
        self.label_10.setText(_translate("MainWindow", "eV"))
        self.deltaE_label.setText(_translate("MainWindow", "DE"))
        self.deltaE_lineEdit.setText(_translate("MainWindow", "0.01"))
        self.label_16.setText(_translate("MainWindow", "eV"))
        self.validate_table_iinputs.setText(_translate("MainWindow", "Validate Table Inputs"))
        self.check_groupBox.setTitle(_translate("MainWindow", "Check"))
        self.label.setText(_translate("MainWindow", "Layer\'s Name"))
        self.label_2.setText(_translate("MainWindow", "Thickness"))
        self.layer_thickness.setText(_translate("MainWindow", "N/A"))
        self.label_4.setText(_translate("MainWindow", "mm"))
        self.label_6.setText(_translate("MainWindow", "Density"))
        self.layer_density.setText(_translate("MainWindow", "N/A"))
        self.label_7.setText(_translate("MainWindow", "g/cm3"))
        self.label_11.setText(_translate("MainWindow", "Element"))
        self.label_15.setText(_translate("MainWindow", "Density"))
        self.element_density.setText(_translate("MainWindow", "N/A"))
        self.label_17.setText(_translate("MainWindow", "g/cm3"))
        self.label_18.setText(_translate("MainWindow", "Molar Mass"))
        self.element_molar_mass.setText(_translate("MainWindow", "N/A"))
        self.label_20.setText(_translate("MainWindow", "g/mol"))
        self.label_14.setText(_translate("MainWindow", "per cm3"))
        self.element_number_of_atoms.setText(_translate("MainWindow", "N/A"))
        self.label_12.setText(_translate("MainWindow", "Number of Atoms"))
        item = self.element_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Isotopes"))
        item = self.element_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Density (g/cm3)"))
        item = self.element_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Iso. Ratio"))
        item = self.element_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Molar Mass (g/mol)"))
        self.label_3.setText(_translate("MainWindow", "Total Iso. Ratio:"))
        self.total_iso_ratio.setText(_translate("MainWindow", "N/A"))
        self.ok_button.setText(_translate("MainWindow", "OK"))

