# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/j35/git/IPTS/notebooks/ui/ui_radial_profile.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(899, 641)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.circle_x = QtGui.QLineEdit(self.groupBox_2)
        self.circle_x.setMaximumSize(QtCore.QSize(50, 16777215))
        self.circle_x.setObjectName(_fromUtf8("circle_x"))
        self.gridLayout.addWidget(self.circle_x, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.circle_y = QtGui.QLineEdit(self.groupBox_2)
        self.circle_y.setMaximumSize(QtCore.QSize(50, 16777215))
        self.circle_y.setObjectName(_fromUtf8("circle_y"))
        self.gridLayout.addWidget(self.circle_y, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sector_full_circle = QtGui.QRadioButton(self.groupBox_3)
        self.sector_full_circle.setChecked(True)
        self.sector_full_circle.setObjectName(_fromUtf8("sector_full_circle"))
        self.verticalLayout_2.addWidget(self.sector_full_circle)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.sector_sector = QtGui.QRadioButton(self.groupBox_3)
        self.sector_sector.setObjectName(_fromUtf8("sector_sector"))
        self.verticalLayout_2.addWidget(self.sector_sector)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sector_from_label = QtGui.QLabel(self.groupBox_3)
        self.sector_from_label.setObjectName(_fromUtf8("sector_from_label"))
        self.gridLayout_2.addWidget(self.sector_from_label, 0, 0, 1, 1)
        self.sector_from_value = QtGui.QLineEdit(self.groupBox_3)
        self.sector_from_value.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sector_from_value.setObjectName(_fromUtf8("sector_from_value"))
        self.gridLayout_2.addWidget(self.sector_from_value, 0, 1, 1, 1)
        self.sector_from_units = QtGui.QLabel(self.groupBox_3)
        self.sector_from_units.setObjectName(_fromUtf8("sector_from_units"))
        self.gridLayout_2.addWidget(self.sector_from_units, 0, 2, 1, 1)
        self.sector_to_label = QtGui.QLabel(self.groupBox_3)
        self.sector_to_label.setObjectName(_fromUtf8("sector_to_label"))
        self.gridLayout_2.addWidget(self.sector_to_label, 1, 0, 1, 1)
        self.sector_to_value = QtGui.QLineEdit(self.groupBox_3)
        self.sector_to_value.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sector_to_value.setObjectName(_fromUtf8("sector_to_value"))
        self.gridLayout_2.addWidget(self.sector_to_value, 1, 1, 1, 1)
        self.sector_to_units = QtGui.QLabel(self.groupBox_3)
        self.sector_to_units.setObjectName(_fromUtf8("sector_to_units"))
        self.gridLayout_2.addWidget(self.sector_to_units, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.guide_red_slider = QtGui.QSlider(self.groupBox_4)
        self.guide_red_slider.setMaximum(255)
        self.guide_red_slider.setOrientation(QtCore.Qt.Horizontal)
        self.guide_red_slider.setObjectName(_fromUtf8("guide_red_slider"))
        self.gridLayout_3.addWidget(self.guide_red_slider, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.guide_green_slider = QtGui.QSlider(self.groupBox_4)
        self.guide_green_slider.setMaximum(255)
        self.guide_green_slider.setOrientation(QtCore.Qt.Horizontal)
        self.guide_green_slider.setObjectName(_fromUtf8("guide_green_slider"))
        self.gridLayout_3.addWidget(self.guide_green_slider, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.guide_blue_slider = QtGui.QSlider(self.groupBox_4)
        self.guide_blue_slider.setMaximum(255)
        self.guide_blue_slider.setOrientation(QtCore.Qt.Horizontal)
        self.guide_blue_slider.setObjectName(_fromUtf8("guide_blue_slider"))
        self.gridLayout_3.addWidget(self.guide_blue_slider, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.guide_alpha_slider = QtGui.QSlider(self.groupBox_4)
        self.guide_alpha_slider.setMaximum(255)
        self.guide_alpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.guide_alpha_slider.setObjectName(_fromUtf8("guide_alpha_slider"))
        self.gridLayout_3.addWidget(self.guide_alpha_slider, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 75))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textBrowser = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 40))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cancel_button = QtGui.QPushButton(self.centralwidget)
        self.cancel_button.setObjectName(_fromUtf8("cancel_button"))
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.apply_button = QtGui.QPushButton(self.centralwidget)
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.horizontalLayout.addWidget(self.apply_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.cancel_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cancel_clicked)
        QtCore.QObject.connect(self.apply_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.apply_clicked)
        QtCore.QObject.connect(self.circle_x, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.circle_center_changed)
        QtCore.QObject.connect(self.circle_y, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.circle_center_changed)
        QtCore.QObject.connect(self.sector_full_circle, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sector_radio_button_changed)
        QtCore.QObject.connect(self.sector_sector, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sector_radio_button_changed)
        QtCore.QObject.connect(self.sector_from_value, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.sector_changed)
        QtCore.QObject.connect(self.sector_to_value, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.sector_changed)
        QtCore.QObject.connect(self.lineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.grid_size_changed)
        QtCore.QObject.connect(self.guide_red_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MainWindow.guide_color_changed)
        QtCore.QObject.connect(self.guide_green_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MainWindow.guide_color_changed)
        QtCore.QObject.connect(self.guide_blue_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MainWindow.guide_color_changed)
        QtCore.QObject.connect(self.guide_alpha_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MainWindow.guide_color_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Circle Center", None))
        self.label.setText(_translate("MainWindow", "x", None))
        self.label_2.setText(_translate("MainWindow", "y", None))
        self.label_4.setText(_translate("MainWindow", "Grid Size", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sector", None))
        self.sector_full_circle.setText(_translate("MainWindow", "Full circle", None))
        self.label_3.setText(_translate("MainWindow", "or", None))
        self.sector_sector.setText(_translate("MainWindow", "Sector", None))
        self.sector_from_label.setText(_translate("MainWindow", "from", None))
        self.sector_from_units.setText(_translate("MainWindow", "degrees", None))
        self.sector_to_label.setText(_translate("MainWindow", "to", None))
        self.sector_to_units.setText(_translate("MainWindow", "degrees", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Guide Color", None))
        self.label_5.setText(_translate("MainWindow", "Red", None))
        self.label_6.setText(_translate("MainWindow", "Green", None))
        self.label_7.setText(_translate("MainWindow", "Blue", None))
        self.label_8.setText(_translate("MainWindow", "Transparency", None))
        self.groupBox.setTitle(_translate("MainWindow", "Instructions", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* Define <span style=\" font-weight:600;\">center of circle</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* Define <span style=\" font-weight:600;\">radial sector</span></p></body></html>", None))
        self.cancel_button.setText(_translate("MainWindow", "Cancel", None))
        self.apply_button.setText(_translate("MainWindow", "OK", None))

