# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/j35/git/IPTS/python_notebooks/ui/ui_water_intake_profile.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 843)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 400))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.file_index_slider = QtWidgets.QSlider(self.layoutWidget)
        self.file_index_slider.setOrientation(QtCore.Qt.Horizontal)
        self.file_index_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.file_index_slider.setTickInterval(1)
        self.file_index_slider.setObjectName("file_index_slider")
        self.horizontalLayout_2.addWidget(self.file_index_slider)
        self.file_index_value = QtWidgets.QLabel(self.layoutWidget)
        self.file_index_value.setObjectName("file_index_value")
        self.horizontalLayout_2.addWidget(self.file_index_value)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.splitter)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setSizeIncrement(QtCore.QSize(50, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.x0 = QtWidgets.QLabel(self.groupBox)
        self.x0.setMinimumSize(QtCore.QSize(100, 0))
        self.x0.setSizeIncrement(QtCore.QSize(100, 0))
        self.x0.setObjectName("x0")
        self.gridLayout.addWidget(self.x0, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.y0 = QtWidgets.QLabel(self.groupBox)
        self.y0.setObjectName("y0")
        self.gridLayout.addWidget(self.y0, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.width = QtWidgets.QLabel(self.groupBox)
        self.width.setObjectName("width")
        self.gridLayout.addWidget(self.width, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.height = QtWidgets.QLabel(self.groupBox)
        self.height.setObjectName("height")
        self.gridLayout.addWidget(self.height, 3, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.add_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.add_radioButton.setChecked(True)
        self.add_radioButton.setObjectName("add_radioButton")
        self.verticalLayout_3.addWidget(self.add_radioButton)
        self.mean_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.mean_radioButton.setObjectName("mean_radioButton")
        self.verticalLayout_3.addWidget(self.mean_radioButton)
        self.median_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.median_radioButton.setObjectName("median_radioButton")
        self.verticalLayout_3.addWidget(self.median_radioButton)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem3 = QtWidgets.QSpacerItem(408, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.help_button = QtWidgets.QPushButton(self.centralwidget)
        self.help_button.setObjectName("help_button")
        self.horizontalLayout.addWidget(self.help_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setMinimumSize(QtCore.QSize(53, 46))
        self.ok_button.setMaximumSize(QtCore.QSize(53, 46))
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_Profile = QtWidgets.QAction(MainWindow)
        self.actionExport_Profile.setObjectName("actionExport_Profile")
        self.actionWater_Intake = QtWidgets.QAction(MainWindow)
        self.actionWater_Intake.setObjectName("actionWater_Intake")
        self.menuFile.addAction(self.actionExport_Profile)
        self.menuFile.addAction(self.actionWater_Intake)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.file_index_slider.valueChanged['int'].connect(MainWindow.slider_changed)
        self.ok_button.clicked.connect(MainWindow.ok_button_clicked)
        self.cancel_button.clicked.connect(MainWindow.cancel_button_clicked)
        self.help_button.clicked.connect(MainWindow.help_button_clicked)
        self.actionExport_Profile.triggered.connect(MainWindow.export_profile_clicked)
        self.actionWater_Intake.triggered.connect(MainWindow.export_water_intake_clicked)
        self.add_radioButton.clicked.connect(MainWindow.profile_algo_changed)
        self.mean_radioButton.clicked.connect(MainWindow.profile_algo_changed)
        self.median_radioButton.clicked.connect(MainWindow.profile_algo_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "File Index"))
        self.file_index_value.setText(_translate("MainWindow", "2"))
        self.label_10.setText(_translate("MainWindow", "NB: First image is ignored"))
        self.groupBox.setTitle(_translate("MainWindow", "Selection"))
        self.label_2.setText(_translate("MainWindow", "X0;"))
        self.x0.setText(_translate("MainWindow", "N/A"))
        self.label_3.setText(_translate("MainWindow", "Y0:"))
        self.y0.setText(_translate("MainWindow", "N/A"))
        self.label_4.setText(_translate("MainWindow", "Width:"))
        self.width.setText(_translate("MainWindow", "N/A"))
        self.label_8.setText(_translate("MainWindow", "Height:"))
        self.height.setText(_translate("MainWindow", "N/A"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Profile Algorithms"))
        self.add_radioButton.setText(_translate("MainWindow", "Add"))
        self.mean_radioButton.setText(_translate("MainWindow", "Mean"))
        self.median_radioButton.setText(_translate("MainWindow", "Median"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.help_button.setText(_translate("MainWindow", "HELP"))
        self.ok_button.setText(_translate("MainWindow", "OK"))
        self.menuFile.setTitle(_translate("MainWindow", "Export"))
        self.actionExport_Profile.setText(_translate("MainWindow", "Profiles ..."))
        self.actionWater_Intake.setText(_translate("MainWindow", "Water Intake ..."))

