button = {'left': {'pressed': 'left_arrow_v2_pressed.png',
                   'released': 'left_arrow_v2_released.png'},
          'right': {'pressed': 'right_arrow_v2_pressed.png',
                    'released': 'right_arrow_v2_released.png'},
          'left_left': {'pressed': 'left_left_arrow_v2_pressed.png',
                        'released': 'left_left_arrow_v2_released.png'},
          'right_right': {'pressed': 'right_right_arrow_v2_pressed.png',
                          'released': 'right_right_arrow_v2_released.png'},
          'up': {'pressed': 'up_arrow_v2_pressed.png',
                 'released': 'up_arrow_v2_released.png'},
          'down': {'pressed': 'down_arrow_v2_pressed.png',
                   'released': 'down_arrow_v2_released.png'},
          'up_up': {'pressed': 'up_up_arrow_v2_pressed.png',
                    'released': 'up_up_arrow_v2_released.png'},
          'down_down': {'pressed': 'down_down_arrow_v2_pressed.png',
                        'released': 'down_down_arrow_v2_released.png'},
          'remote_control': {'pressed': 'remote_control_pressed.png',
                             'released': 'remote_control_released.png'}
          }
