list_pvs = {'daq-rate': {'path': ['entry', 'DASlogs', 'BL10:Det:BM1:Histo:Daq:Rate'],
                         'label': 'BM count rate on BM controller',
                        },
            'event_rate_rbv': {'path': ['entry', 'DASlogs', 'BL10:Det:M1:Det1:EventRate_RBV'],
                                'label': 'BM count rate from ADnED',
                              },
            'count_rate': {'path': ['entry', 'DASlogs', 'BL10:Det:T1:CountRate_RBV'],
                           'label': 'TPX3 count rate from ADtED',
                            },
            'pel_evt_rate': {'path': ['entry', 'DASlogs', 'BL10:CS:tpx3:cam1:PelEvtRate_RBV'],
                            'label': 'TPX3 count rate on Serval',
                            },
            'discr_read': {'path': ['entry', 'DASlogs', 'BL10:Det:BM1:Discr:Read'],
                           'label': 'Beam monitor discriminator threshold'},
            'volt_alarm': {'path': ['entry', 'DASlogs', 'BL10:Det:BM1:HV:VoltAlarm'],
                           'label': 'Beam monitor HV',
                             },
            }